name: Ubuntu
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

      # Step 1. Checkout repo.
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2. Install python.
      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          sudo apt-get install -y pip

      # Step 3. Install tox
      - name: Install tox
        run: |
          python3 -m pip install tox

      - name: Run tests
        run: |
          tox
